export const adulto = [
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '17F',
    color: 'Todos',
    medidas: '42,5 X 21,5 X 0,56 cm',
    prendas: 'Camisas,Camisetas,Busos,Chalecos,Blusas y Tops',
    img: '',
    glb: '../../../assets/glb/17F.glb',
  },
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '18A',
    color: 'Todos',
    medidas: '39,2 X 21 X 0,61 cm',
    prendas: 'Superiores , inferiores y Conjunto',
    img: '',
    glb: '../../../assets/glb/18A.glb',
  },
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '30B',
    color: 'Todos',
    medidas: '30,2 X 23,5 X 1,38 cm',
    prendas: 'Pantalones, Patalonetas , Sudaderas , Faldas y Shorts',
    img: '',
    glb: '',
  },
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '30BPL',
    color: 'Todos',
    medidas: '30,2 X 22,6 X 1,38 cm',
    prendas: 'Pantalones, Patalonetas , Sudaderas , Faldas y Shorts',
    img: '',
    glb: '',
  },
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '30BPL',
    color: 'Todos',
    medidas: '35 X 20,3 X 1,41 cm',
    prendas: 'Pantalones, Patalonetas , Sudaderas , Faldas y Shorts',
    img: '',
    glb: '',
  },
];
