const adultoPremium = [
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '38',
    color: 'Todos',
    medidas: '40,7X 21 X 1,07 cm',
    prendas: 'Camisas,Camisetas,Busos,Chalecos,Blusas',
    img: '',
    glb: '../../../assets/glb/38.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '386',
    color: 'Todos',
    medidas: '43,6X 22,5 X  0,97cm',
    prendas: 'Camisas,Camisetas,Busos,Chalecos,Blusas',
    img: '',
    glb: '../../../assets/glb/386.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '6E',
    color: 'Todos',
    medidas: '40,5X 20,7 X 0,96 cm',
    prendas: 'Camisas,Camisetas,Busos,Chalecos,Blusas',
    img: '',
    glb: '',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '491B',
    color: 'Todos',
    medidas: '46,5X 24 X 0,96,cm',
    prendas: 'Superiores , inferiores y Conjunto',
    img: '',
    glb: '../../../assets/glb/491B.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '32',
    color: 'Todos',
    medidas: '45,5X 24,4 X 3,5cm',
    prendas: 'Trajes Completos, Vestidos formales, Chaquetas',
    img: '',
    glb: '../../../assets/glb/32.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '393',
    color: 'Todos',
    medidas: '33,4X 12,5 X 2,7cm',
    prendas: 'Pantalones, Pantalonetas,Sudaderas,Faldas y Shorts',
    img: '',
    glb: '',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '493A',
    color: 'Todos',
    medidas: '36,5X 19,3 X 0,95cm',
    prendas: 'Pantalones, Pantalonetas,Sudaderas,Faldas y Shorts',
    img: '',
    glb: '../../../assets/glb/493A.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '386B',
    color: 'Todos',
    medidas: '36,5X 19,3 X 0,95cm',
    prendas: 'Superior, Inferior , Conjuntos y Vestidos de baño',
    img: '',
    glb: '../../../assets/glb/493A.glb',
  },
];
