export const infantil = [
  {
    line: 'infantil',
    ropa: 'Infantil',
    ref: '12F',
    color: 'Todos',
    medidas: '31,5 X 19,5 X 0,5 cm',
    prendas: 'Camisas,Camisetas,Busos,Pantalones,jeans,sudaderas y faldas',
    img: '',
    glb: '../../../assets/glb/12F.glb',
  },
  {
    line: 'infantil',
    ropa: 'Infantil',
    ref: '11-3',
    color: 'Todos',
    medidas: '22 X 16,4 X 0,61 cm',
    prendas: '2 a 5 prendas como camisas camsetas(bodies)',
    img: '',
    glb: '../../../assets/glb/11-3.glb',
  },
  {
    line: 'infantil',
    ropa: 'Infantil',
    ref: '12-10',
    color: 'Todos',
    medidas: '30,2 X 29,5 X 0,47 cm',
    prendas: 'Conjuntos, prendas modelado perfecto',
    img: '',
    glb: '../../../assets/glb/12F.glb',
  },
  {
    line: 'infantil',
    ropa: 'Infantil',
    ref: '13A',
    color: 'Todos',
    medidas: '28,2 X 37,1 X 0,46 cm',
    prendas: 'Conjuntos, prendas modelado perfecto',
    img: '',
    glb: '',
  },
];
