export const products = [
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '17F',
    color: 'Todos',
    medidas: '42,5 X 21,5 X 0,56 cm',
    prendas: 'Camisas,Camisetas,Busos,Chalecos,Blusas y Tops',
    img: '',
    glb: '../../../assets/glb/17F.glb',
  },
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '18A',
    color: 'Todos',
    medidas: '39,2 X 21 X 0,61 cm',
    prendas: 'Superiores , inferiores y Conjunto',
    img: '',
    glb: '../../../assets/glb/18A.glb',
  },
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '30B',
    color: 'Todos',
    medidas: '30,2 X 23,5 X 1,38 cm',
    prendas: 'Pantalones, Patalonetas , Sudaderas , Faldas y Shorts',
    img: '',
    glb: '',
  },
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '30BPL',
    color: 'Todos',
    medidas: '30,2 X 22,6 X 1,38 cm',
    prendas: 'Pantalones, Patalonetas , Sudaderas , Faldas y Shorts',
    img: '',
    glb: '',
  },
  {
    line: 'adulto',
    ropa: 'Adulto',
    ref: '30BPL',
    color: 'Todos',
    medidas: '35 X 20,3 X 1,41 cm',
    prendas: 'Pantalones, Patalonetas , Sudaderas , Faldas y Shorts',
    img: '',
    glb: '',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '38',
    color: 'Todos',
    medidas: '40,7X 21 X 1,07 cm',
    prendas: 'Camisas,Camisetas,Busos,Chalecos,Blusas',
    img: '',
    glb: '../../../assets/glb/38.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '386',
    color: 'Todos',
    medidas: '43,6X 22,5 X  0,97cm',
    prendas: 'Camisas,Camisetas,Busos,Chalecos,Blusas',
    img: '',
    glb: '../../../assets/glb/386.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '486E',
    color: 'Todos',
    medidas: '40,5X 20,7 X 0,96 cm',
    prendas: 'Camisas,Camisetas,Busos,Chalecos,Blusas',
    img: '',
    glb: '../../../assets/glb/486E.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '491B',
    color: 'Todos',
    medidas: '46,5X 24 X 0,96,cm',
    prendas: 'Superiores , inferiores y Conjunto',
    img: '',
    glb: '../../../assets/glb/491B.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '32',
    color: 'Todos',
    medidas: '45,5X 24,4 X 3,5cm',
    prendas: 'Trajes Completos, Vestidos formales, Chaquetas',
    img: '',
    glb: '../../../assets/glb/32.glb',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '393',
    color: 'Todos',
    medidas: '33,4X 12,5 X 2,7cm',
    prendas: 'Pantalones, Pantalonetas,Sudaderas,Faldas y Shorts',
    img: '',
    glb: '',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '493A',
    color: 'Todos',
    medidas: '36,5X 19,3 X 0,95cm',
    prendas: 'Pantalones, Pantalonetas,Sudaderas,Faldas y Shorts',
    img: '',
    glb: '',
  },
  {
    line: 'adultopremium',
    ropa: 'Adulto Premium',
    ref: '386B',
    color: 'Todos',
    medidas: '36,5X 19,3 X 0,95cm',
    prendas: 'Superior, Inferior , Conjuntos y Vestidos de baño',
    img: '',
    glb: '',
  },
  {
    line: 'junior',
    ropa: 'Junior',
    ref: '9A',
    color: 'Todos',
    medidas: '27 X 17,6 X 0,9 cm',
    prendas: 'Camisas,Camisetas,Busos,Pantalones,jeans,sudaderas y faldas',
    img: '',
    glb: '../../../assets/glb/9A.glb',
  },
  {
    line: 'junior',
    ropa: 'Junior',
    ref: '480J',
    color: 'Todos',
    medidas: '37 X 20 X 0,67 cm',
    prendas: 'Camisas,Camisetas,Busos,Pantalones,jeans,sudaderas y faldas',
    img: '',
    glb: '../../../assets/glb/480J.glb',
  },
  {
    line: 'junior',
    ropa: 'Junior',
    ref: '486E',
    color: 'Todos',
    medidas: '30,3 X 15,3 X 2,5 cm',
    prendas: 'Camisas,Camisetas,Busos,Pantalones,jeans,sudaderas y faldas',
    img: '',
    glb: '../../../assets/glb/486E.glb',
  },
  {
    line: 'infantil',
    ropa: 'Infantil',
    ref: '12F',
    color: 'Todos',
    medidas: '31,5 X 19,5 X 0,5 cm',
    prendas: 'Camisas,Camisetas,Busos,Pantalones,jeans,sudaderas y faldas',
    img: '',
    glb: '',
  },
  {
    line: 'infantil',
    ropa: 'Infantil',
    ref: '11-3',
    color: 'Todos',
    medidas: '22 X 16,4 X 0,61 cm',
    prendas: '2 a 5 prendas como camisas camsetas(bodies)',
    img: '',
    glb: '../../../assets/glb/11-3.glb',
  },
  {
    line: 'infantil',
    ropa: 'Infantil',
    ref: '12-10',
    color: 'Todos',
    medidas: '30,2 X 29,5 X 0,47 cm',
    prendas: 'Conjuntos, prendas modelado perfecto',
    img: '',
    glb: '',
  },
  {
    line: 'infantil',
    ropa: 'Infantil',
    ref: '13A',
    color: 'Todos',
    medidas: '28,2 X 37,1 X 0,46 cm',
    prendas: 'Conjuntos, prendas modelado perfecto',
    img: '',
    glb: '',
  },
  {
    line: 'Infantilpremium',
    ropa: 'Infantil Premium',
    ref: '497',
    color: 'Todos',
    medidas: '23,7 X 17,7 X 0,7 cm',
    prendas: 'Camisas,Camisetas,Busos,Chalecos,Blusas',
    img: '',
    glb: '',
  },
  {
    line: 'Infantilpremium',
    ropa: 'Infantil Premium',
    ref: '13EA',
    color: 'Todos',
    medidas: '30 X 39,9 X 0,45 cm',
    prendas: 'Conjuntos, prendas modelado perfecto',
    img: '',
    glb: '',
  },
  {
    line: 'interiorfemenino',
    ropa: 'Interior femenino',
    ref: '2C',
    color: 'Todos',
    medidas: '27,5 X 9,5 X 0,59 cm',
    prendas: 'Pantys,Brasier y Prendas Deportivas',
    img: '',
    glb: '',
  },
  {
    line: 'interiorfemenino',
    ropa: 'Interior femenino',
    ref: '6B',
    color: 'Todos',
    medidas: '25,5 X 11,6 X 0,65 cm',
    prendas: 'Pantys,Brasier y Prendas Deportivas',
    img: '',
    glb: '',
  },
  {
    line: 'interiorfemenino',
    ropa: 'Interior femenino',
    ref: '7-3',
    color: 'Todos',
    medidas: '30,6 X 16,3 X 2,08 cm',
    prendas: 'Pantys,Brasier y Prendas Deportivas',
    img: '',
    glb: '',
  },
  {
    line: 'interiormasculina',
    ropa: 'Interior Masculina',
    ref: '04A-3',
    color: 'Todos',
    medidas: '30,6 X 16,3 X 2,08 cm',
    prendas: 'Medias, Leggins,Pantaloncillos, Bóxer',
    img: '',
    glb: '',
  },
];
